### ISSUE TITLE
When compilation fails, seems like it reverts generated files to an old state?

### ISSUE THREAD

**Issue by phated** [zth/vscode-reason-relay#2]
Sometimes, when the relay compiler fails (and I'm notified with the pop up), it reverts one of my generated files to use an old customScalar: I had it defined as `Date.t` briefly but immediately changed it to `string` and it keeps switching between them.

**Comment by zth** [comment]
Hopefully fixed in https://github.com/zth/vscode-reason-relay/commit/3c5940ea0a1b1c6d256433b79ea207ea874bb643.
