### ISSUE TITLE
Really long name in toolbar

### ISSUE THREAD

**Issue by phated** [zth/vscode-reason-relay#3]
Just a little nitpick. The message about the compiler running in the toolbar is really long compared to everything else.

<img width="595" alt="Screen Shot 2020-04-25 at 8 06 57 PM" src="https://user-images.githubusercontent.com/992373/80296469-71769c00-8730-11ea-9c70-8d076265f2a6.png">

**Comment by zth** [comment]
Yes, that's mostly because I'm (ab)using it to report things. I'll try and make it a bit more compact.

**Comment by zth** [comment]
Somewhat improved in https://github.com/zth/vscode-reason-relay/commit/209e8292300c9bc3aa06913c58396b6f25f1dd3d.
