### ISSUE TITLE
Popups are very annoying

### ISSUE THREAD

**Issue by phated** [zth/vscode-reason-relay#4]
This plugin is doing a lot in the background and getting all the notifications that don't close themselves is pretty annoying. Usually, if I want to debug something, I'll be developing with the "Problems" or "Output" tab open.

<img width="566" alt="Screen Shot 2020-04-25 at 8 08 59 PM" src="https://user-images.githubusercontent.com/992373/80296487-a256d100-8730-11ea-8660-f88e62c72d7d.png">

**Comment by zth** [comment]
😅 

I think I'll move to only using the status bar item instead, and people can (just like you say) go to the actual output pane to see the error. Would that improve things?

**Comment by phated** [comment]
I'd love for the "Relay Compiler error" to be reported in the "Problems" tab and any issues with the plugin or other debug information to be displayed in the "Output" tab.

**Comment by zth** [comment]
Somewhat fixed in https://github.com/zth/vscode-reason-relay/commit/08e6573a4fc5ce248f1049ee570138e8cba7b92b.

This will all be much better when the official Relay LSP is released and integrated with this extension. Any year now! ;)
