### ISSUE TITLE
Code actions seem to remove comments inside a query

### ISSUE THREAD

**Issue by phated** [zth/vscode-reason-relay#5]
I tried out the "extract selected field to new fragment component" code action and it removed the code comment I had added to my query.

**Comment by zth** [comment]
This is really unfortunate, but from what I can see, this seems to be because the `graphql` parser simply does not include the comments. I'll try and look into this some more.

**Comment by zth** [comment]
No clear way forward here without changing the underlying technical completely unfortunately. I'll close this for now and revisit at a later point.
