### ISSUE TITLE
Code action: expansion on interfaces seem to only expand one (the first?) interface

### ISSUE THREAD

**Issue by phated** [zth/vscode-reason-relay#6]
I have objects that implement multiple interfaces (Node & Card) and when I tried the code action to expand the interface, it only expanded to include `{ id }` on each implementation.

**Comment by zth** [comment]
You're referring to that `id` is the only field automatically added, right? At this point, that's actually the intended behavior, it should expand all union/interface _members_, but it'll only select the first field (or `id` if that exists) of the specified member. 

Maybe if I re-word the action to "Expand union members"?

**Comment by phated** [comment]
Ah, it's probably just a documentation issue in the README then. I assumed it would expand the entire interface/union so I could highlight the fields and use the other action to extra to a fragment.

**Comment by zth** [comment]
Clarified in https://github.com/zth/vscode-reason-relay/commit/497e9e2e8de925f60769d0b7d7691bde1696abf7.
